name: .NET Core

on:
  push:
    branches: [ main, DanielGoehler-patch-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./XliffCheck/XliffCheck.sln
    - name: Build
      run: dotnet build ./XliffCheck/XliffCheck.sln --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ./XliffCheck/XliffCheck.sln 
